/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicReadmeDotsvgRouteImport } from './routes/api/public/readme[.]svg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReadmeDotsvgRoute = ApiPublicReadmeDotsvgRouteImport.update({
  id: '/api/public/readme.svg',
  path: '/api/public/readme.svg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/readme.svg': typeof ApiPublicReadmeDotsvgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/readme.svg': typeof ApiPublicReadmeDotsvgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/readme.svg': typeof ApiPublicReadmeDotsvgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/readme.svg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/readme.svg'
  id: '__root__' | '/' | '/api/public/readme.svg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicReadmeDotsvgRoute: typeof ApiPublicReadmeDotsvgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/readme.svg': {
      id: '/api/public/readme.svg'
      path: '/api/public/readme.svg'
      fullPath: '/api/public/readme.svg'
      preLoaderRoute: typeof ApiPublicReadmeDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicReadmeDotsvgRoute: ApiPublicReadmeDotsvgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
